version: "3.9"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    restart: on-failure
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - grafana-storage:/var/lib/grafana

  golang:
    container_name: golang_container
    build:
      dockerfile: Dockerfile
    environment:
      - STAGE=${STAGE}
      - SQS_URL=${SQS_URL}
      - AWS_TOKEN=${AWS_TOKEN}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - grafana
      - prometheus
    # For Dockerfile.Local only
    # volumes:
    #   - ./:/app

volumes:
  grafana-storage: {}
